class Config:
    SP_VOCAB_SIZE = 1000
    SP_CHARACTER_COVERAGE = 0.9990
    SP_MODEL_TYPE = 'unigram'
    CBOW_WINDOW_SIZE = 5
    W2V_EMBEDDING_DIM = 50
    TWO_TOWER_HIDDEN_DIM = 128
    TWO_TOWER_OUTPUT_DIM = 64
